### ISSUE TITLE
Can't get isValid() to return true

### ISSUE THREAD

**Issue by pedrosancheznery** [ludbek/powerform#20]
I'm using it with mithril.
Here's my partial code:
`
var SignUpForm = {
  form: powerform({
    username: {
      // default: "",
      validator: [required(true), minLength(2)]
    },
    password: {
      // default: "",
      validator: [required(true), minLength(2)]
    },
    confirmPassword: {
      // default: "",
      validator: [required(true), minLength(2), equalsTo("password")]
    }
  }, true)
  ,
  submit: function() {
    console.log("form", this.username.isValid())
    if(!this.form.isValid()) 
      return SignupAPI(this.form.data())
        .then((res) => {
          m.route("/login/")})
        ["catch"]((errors) => {
          this.form.error(errors)})
        .then(()=> m.redraw())
      }
}

let signup = {
  oninit: function (vnode) {
    console.log(`%c oninit`, 'background: #222; color: #bada55')
    vnode.state = SignUpForm
    vnode.state.form.username.setAndValidate("");
    vnode.state.form.password.setAndValidate("");
    vnode.state.form.confirmPassword.setAndValidate("");
  },
  view: function (vnode) {
    return m("form.uk-form-stacked",
      m("input.uk-input", {
        placeholder: "Username",
        onkeypress: m.withAttr("value", vnode.state.form.username),
        // value: vnode.state.username(),
        onblur: m.withAttr("value", (val) =>{vnode.state.form.username.setAndValidate(val);console.log(`Username: ${val}`)})
      }),
      vnode.state.form.username.error().map( (error) => m("p.uk-text-danger", error) ),
      m("input.uk-input[type=password]", {
        placeholder: "Password",
        onkeypress: m.withAttr("value", vnode.state.form.password),
        // onchange: vnode.state.form.password.isValid()
        onblur: m.withAttr("value", (val) =>{vnode.state.form.password.setAndValidate(val);console.log(`Password: ${val}`)})
      }),
      vnode.state.form.password.error().map( (error) => m("p.uk-text-danger", error) ),
      m("input.uk-input[type=password]", {
        placeholder: "Confirm Password",
        onkeypress: m.withAttr("value", vnode.state.form.confirmPassword),
        // onchange: vnode.state.form.confirmPassword.isValid()
        onblur: m.withAttr("value", (val) =>{vnode.state.form.confirmPassword.setAndValidate(val);console.log(`confir: ${val}`)})
      }),
      vnode.state.form.confirmPassword.error().map( (error) => m("p.uk-text-danger", error) ),
      m("button.uk-button.uk-button-primary", {
        disabled: !vnode.state.form.isValid(false),
        // onclick: vnode.state.form.submit(vnode)
      }, "Submit")
    )
  }
}
`

I cant't get to the submit button because the form.isValid() is always false

**Comment by ludbek** [comment]
This looks like a bug. I am digging it. Thanx for reporting :)

**Comment by ludbek** [comment]
It has been fixed it `v2.6.7` please update your powerform version.

Check this [demo](http://jsbin.com/cozulez/1/edit?html,output).
