### ISSUE TITLE
Mithril example is out of date

### ISSUE THREAD

**Issue by ArthurClemens** [ludbek/powerform#27]
Here is an [example that works with Mithril 1.x](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxHKYnAATAtAJ0QBHAK7kD+IlqPHM8GABUIWsVoC8WgG63y+TIIAeANwAOlBa4RGhGtoAgtjYbjqh4dDkUOScKFqkxlBgnOTQABQeUBD4iACUSWERpeWIrJp+iInAyRHhpBB6jFnYEADuiHrdvUXttZ3hxnh6DMxZk9PTFaSYxvCZWsEgu0QdK+Fe8D5+PVk0h0fhBiZmBEWcesZV1ysAuu8REt-h2JgYDBBj18Es-hE1hstlldvsIcdvL5OBd9NYHvgni83lNpr9cZ1lBRegAFQHA0HggmrRDrTbbOHEBGeJHnPSXZm3dHmLGvSoHakray2BwQIq7AFAkF6fC7SrMr6C5zfMT874wYwAI0YGSyOTyBWgWiK1WWR3qFSanBaTS1Os4ADFMJQCIl1nZEIEtAB6b1ovCcCHkUjGgCEFsazUErDGjFY5BgADUkSbTcyI1abRrtRknS78Ilnq8QkquZxjPNsiLPRCxBDfVoAMojDwjLQwHytE5nQ1Qet+5tQAuxrTIzBaFFaGIkgCSrHnWk1xm0aU0iEwBeGWkGlHgWjks20MHYQy0szbpEQBE1mDAAGsIRmo5G7RlBAX3EWa0qn9bo9n7TzJAPyrD0SxuAxy0rd08HAvEBRWADc2dYC9WrBDpiQzh3zQj1rjrWp8WOchEEGPVcnyQowhKMoKjTXFonbP9WncX8Wjg8JGJHdxnxjHpGA4rRGJGPQehgN1+NYESehNQTGKwoDXR45jbRzR0UIIOToE0bJ+IAUT0US9HE5SbVjAyjJgQTIIrMJeKw99vgAfi0RhxRAdgAGZ9h2EAAE0IGMAByAxR2gRBQzlb4sjc3ZY3hJVdG019tnslLnAwlYrlLVz3PYABGHzdkbcgAHMwmMbA5Uyo5YtkUTBh87Kbk6Oq0mwZcfLNFqIgWRBYRAc95mkBKes6bAsDARAT3gCp2V8gBVOY+tGsaUnSKAOu2OMd04dgYmwvR3JOV4fNjVghr6tUcs6aAwHYTAoFK-rdN6C7lukeMkyRTlnGutaFI0gsADJga0UNzsuz6E2TU5MWqUHcolKTDJ6M7JKh5gUaM1Mas+f6Wrq1gGqa362s2zriBqNbwj6gbJQpGVVrWibb2mhA5oGskpVBZmxtSCnttYXb9sO47bFOqnzoZ6V8AJta7oep6Xul8lZa+2GfF+1U8aOQH8y0RGIckmXQQ1lMEbBursGxtGpZNtWzeko7Knlo4PjdlYiZJqnmrG8mtq637aekAaiTMRhucZ2UmRuiJWammbOd8gBhaBiUYLRTaZ2Oaa0AWtpi4WMlF55xfgSXLHO8PSUdmVPZaxXHuevVJJryO6-wc24e1hvEJSxSQbB423vbqP1Zhi3Dat9ybed9HR-TiPx6d1GXb7iIPd11r3OJoZSbjuql2w6Ag7j9awFOe8sjStTtcsYqhBj+Uco9iFFRWSo4IIgjQjjRhAoCCKPgCAYBjDMAEKwTU5QACelg4jYC-qEcQkgQB9REKwMAQI+DKEEMINA0D8AwOprpAQABadYOp4AwJvo9GAZC5jBhLARPegwtAAGotCsJIYwTAehSppDISibAWR8oGAEqEAic8148L4QIqAWRWAAFZxFaAAAzqPUXBSA8BUTmGYeID4JBThQDvNQFAdA0HSBEPadgehKB8ArLwNAXBOC4BQL6XI2A7ylUwRARg3pbH2PgAAAXyqwcJSjAkl2CfIRQIBOAwOwDIBQKCpDMBEN2ZEiB-CsB1FAOJji9DOI8thdxnjNo+L8QErJLR-AhLUawTyETvT4ATJwb0tSAh5LSIUkgiTkkiFSRIdJMgBjDFGJJfJfTBrFJEK48p3ovFVMgAE8ZIxYwhIAEysAABysDUa09p3p1mTLetM1J-SkkpOoGID4YggA)

**Comment by ludbek** [comment]
Thanks linked your example in readme.
