### ISSUE TITLE
Form with nested props

### ISSUE THREAD

**Issue by cristianp6** [ludbek/powerform#29]
First of all thank you for this nice library!

I'm looking to create a proper `powerform` instance for objects with structure like this:
```javascript
const fields = {
  "name": "Name value",
  "metadata": {
    "notes": "These are some notes",
    "email": "my@email.com",
    ...
  }
}
```
My validation rules object is like:
```javascript
const validations = {
  name: {
    default: "Name value",
    validator: (value) => { ... }
  },
  metadata: {
    default: {},
    validator: (value) => { ... },
    notes: {
      default: "These are some notes",
      validator: (value) => { ... }
    },
    ...
  }
}
```

The I instantiate `powerform` with:
```javascript
const form = powerform(validations)
```
As you can see in the `form.metadata` prop there isn't any nested field (notes, email, etc.):

![form](https://user-images.githubusercontent.com/233734/33944032-301e6968-e01b-11e7-9eb2-e01fb22340d6.png)

Am I missing something or doing it wrong?
Are nested fields accepted?

Thanks!

**Comment by ludbek** [comment]
@cristianp6 Thanks for kind words.

Unfortunately, `powerform` does not support nested validations for now.
For the problem you are facing, could you try following solution?

```javascript
const metadataSchema = {
  notes: {},
  email: {}
}

const validations = {
  name: {
    default: "Name value",
    validator: (value) => { ... }
  },
  metadata: {
    default: {},
    validator: (value) => {  return validate(value, metadataSchema)}  
  }
}
```

**Comment by cristianp6** [comment]
Thanks, I'll try your solution.

Meanwhile I've done a dirty trick renaming nested object keys to `metadata.notes`, `metadata.email`, etc. so I have a "flattened" object on which I create all the validations and instantiate `powerform`.
Then, after the `isValid()` check, I go back to the original object structure "unflattening" all props.
It works.

**Comment by ludbek** [comment]
Cool.
Just out of curiosity, what is the use case that you are into?
Is it being used for data validation or form validation?

**Comment by cristianp6** [comment]
It's for form validation

**Comment by ludbek** [comment]
Closing this.
