### ISSUE TITLE
Add example with form fields

### ISSUE THREAD

**Issue by ArthurClemens** [ludbek/powerform#31]
I am missing an example using a form and input fields.

**Comment by ludbek** [comment]
Sorry could you be more specific? If you are referring to the examples there is an example usage with [Mithril here](https://codesandbox.io/s/nr4lxn4ovm) :)

**Comment by ArthurClemens** [comment]
ok, that helps. I couldn't find it in the readme.

**Comment by ludbek** [comment]
Actually its under the section, Showcase.
